import gradio as gr
import asyncio
import os
from pathlib import Path
from graph import run_pipeline

OUTPUT_BASE = "generated_apps"


async def generate(user_idea: str, progress=gr.Progress()):
    if not user_idea.strip():
        yield "⚠️ Please describe your app idea first."
        return

    # Create a unique output dir per run
    import uuid
    run_id = uuid.uuid4().hex[:12]
    output_dir = os.path.join(OUTPUT_BASE, run_id)
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    async for update in run_pipeline(user_idea, output_dir=output_dir):
        yield update

    yield update + f"\n\n📁 Files saved to: `{output_dir}/`"


with gr.Blocks(
    title="Vibe Coding",
    theme=gr.themes.Default(primary_hue="violet", neutral_hue="slate"),
    css="""
    .contain { max-width: 1000px; margin: 0 auto; }
    footer { display: none !important; }
    """
) as ui:

    gr.Markdown("""
# ⚡ Vibe Coding
### Describe your app — get a full-stack React + FastAPI app generated by AI agents.
""")

    with gr.Row():
        with gr.Column(scale=1):
            idea_input = gr.Textbox(
                label="Your app idea",
                placeholder=(
                    "e.g. A project management tool where teams can create projects, "
                    "add tasks with deadlines and priorities, assign them to members, "
                    "and track progress on a kanban board."
                ),
                lines=6,
            )

            with gr.Row():
                clear_btn = gr.Button("Clear", variant="secondary")
                generate_btn = gr.Button("⚡ Generate App", variant="primary", scale=2)

            gr.Markdown("""
**What you'll get:**
- 🗄️ FastAPI backend with SQLAlchemy
- ⚛️ React + Tailwind frontend (dark, professional)
- 🔄 Evaluator loop that reviews and fixes issues
- 📖 README with run instructions
""")

        with gr.Column(scale=2):
            output = gr.Markdown(
                label="Agent Output",
                value="Your generated app will appear here...",
            )

    generate_btn.click(fn=generate, inputs=idea_input, outputs=output)
    idea_input.submit(fn=generate, inputs=idea_input, outputs=output)
    clear_btn.click(fn=lambda: ("", "Your generated app will appear here..."),
                    outputs=[idea_input, output])


if __name__ == "__main__":
    ui.launch(inbrowser=True)
